name: Build ARM64

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string
      push:
        description: 'Whether to push the image'
        required: false
        type: boolean
        default: false
    outputs:
      image-digest:
        description: 'Docker image digest'
        value: ${{ jobs.build-arm64.outputs.digest }}

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/kube-health-reporter

jobs:
  build-arm64:
    name: Build Docker image for ARM64
    runs-on: ubuntu-24.04-arm64
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive version from tag
        id: ver
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
            echo "push=true" >> "$GITHUB_OUTPUT"
          else
            echo "version=${{ inputs.version }}" >> "$GITHUB_OUTPUT"
            echo "push=${{ inputs.push }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: ${{ steps.ver.outputs.push == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (arm64)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: ${{ steps.ver.outputs.push == 'true' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.version }}-arm64
            ${{ env.IMAGE_NAME }}:latest-arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=${{ steps.ver.outputs.push == 'true' }},name-canonical=true,push=${{ steps.ver.outputs.push == 'true' }}

      - name: Export digest
        if: ${{ steps.ver.outputs.push == 'true' }}
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        if: ${{ steps.ver.outputs.push == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: digests-arm64
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
