name: Release

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'

permissions:
  contents: write     # create GitHub Release
  packages: write     # push to GHCR (docker + helm)

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/kube-health-reporter
  CHART_DIR: helm/kube-health-reporter

jobs:
  release:
    name: Build and publish Docker image and Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive version from tag
        id: ver
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (Docker)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (amd64 + arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Log in to GHCR (Helm OCI)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username "${{ github.actor }}" --password-stdin

      - name: Package Helm chart
        run: |
          mkdir -p dist
          helm package "$CHART_DIR" \
            --version "${{ steps.ver.outputs.version }}" \
            --app-version "${{ steps.ver.outputs.version }}" \
            --destination dist

      - name: Push Helm chart to GHCR (OCI)
        run: |
          helm push "dist/kube-health-reporter-${{ steps.ver.outputs.version }}.tgz" \
            oci://ghcr.io/${{ github.repository_owner }}

      - name: Create GitHub Release and upload Helm chart asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/kube-health-reporter-${{ steps.ver.outputs.version }}.tgz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


